spring:
  application:
    name: patholabintellect
  datasource:
    url: jdbc:postgresql://localhost:5432/patholabintellect
    username: postgres
    password: adept
    driver-class-name: org.postgresql.Driver